name: Generate SBOM

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CycloneDX Node module
        run: npm install -g @cyclonedx/bom

      - name: Install project dependencies
        run: npm install

      - name: Generate SBOM
        run: cyclonedx-bom -o sbom.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
